### ISSUE TITLE
Doc-130323--001

### ISSUE THREAD

**Issue by dowesw** [dowesw/tne#1]
Aperçu du cite courant, Donner ses impressions et Avis
Proposition de mise a jour ou refonte du site TNE

**Comment by Podolski237** [comment]
Très beau design du site,les interfaces sont bien travaillé , présentation des images très dynamique
Page d'accueil du peu trop surchargé selon moi mais dans l'ensemble c'est très bien fait.

**Comment by dowesw** [comment]
Conclusion : **mise à jour du site existant**
