### ISSUE TITLE
Doc-150323--001

### ISSUE THREAD

**Issue by dowesw** [dowesw/tne#2]
Organisation du site  (_prendre connaissance de ce qui existe_)
- liste des différentes pages
- structure de la navigation
- découpage des parties de chaque page

**Comment by Podolski237** [comment]
pour moi tant que l'organisation est clair, simple et précis le site est bien réalisé

**Comment by Podolski237** [comment]
[liste des differentes pages web.docx](https://github.com/dowesw/tne/files/11049337/liste.des.differentes.pages.web.docx)

**Comment by Podolski237** [comment]
[structure de la navigation.docx](https://github.com/dowesw/tne/files/11049344/structure.de.la.navigation.docx)

**Comment by dowesw** [comment]
> [liste des differentes pages web.docx](https://github.com/dowesw/tne/files/11049337/liste.des.differentes.pages.web.docx)

- les produits ne sont pas gérés individuellement? 
- les services ne sont pas gérés individuellement?

La liste des pages fournis n'est pas complet. tu dois te balader sur le site afin de recenser toutes les pages

**Comment by Podolski237** [comment]
[decoupage de pages.docx](https://github.com/dowesw/tne/files/11089080/decoupage.de.pages.docx)
[liste des differentes pages web.docx](https://github.com/dowesw/tne/files/11089081/liste.des.differentes.pages.web.docx)
